language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - add-on

before_install:
    - git clone https://github.com/simpligility/maven-android-sdk-deployer.git
    - cd maven-android-sdk-deployer
    - mvn install -P 5.1
    - cd ..

install: mvn clean install

script: mvn checkstyle:checkstyle

